// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvjJQX0hIyHveEqCM348b17GmMHoiF8gM',
    appId: '1:263814749904:android:df29453ee78baeab44c8d5',
    messagingSenderId: '263814749904',
    projectId: 'flutter-deadline-management',
    storageBucket: 'flutter-deadline-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLSH5acjV11CP98uisQEIreauWqRrdb2k',
    appId: '1:263814749904:ios:edbebddc951b12d544c8d5',
    messagingSenderId: '263814749904',
    projectId: 'flutter-deadline-management',
    storageBucket: 'flutter-deadline-management.appspot.com',
    iosClientId: '263814749904-d340q7mv0640sge550oq3lt46so0e3d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDeadlineManagem',
  );
}
